services:
    app:
        build:
            context: .
            dockerfile: docker/app.Dockerfile
        image: mylaravel/php82-app
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - './:/var/www/html'
            - 'vendor_data:/var/www/html/vendor'
            - './docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro'
        command: >
            sh -c "
            chown -R www-data:www-data /var/www/html/storage &&
            chmod -R 775 /var/www/html/storage &&
            php-fpm
            "
        env_file:
            - .env
        networks:
            - app-network
    web:
        image: 'nginx:latest'
        container_name: web
        restart: unless-stopped
        ports:
            - '8080:80'
        volumes:
            - './:/var/www/html:ro'
            - './docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro'
        networks:
            - app-network
    mysql:
        image: 'mysql:8.0'
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: '${DB_DATABASE:-database}'
            MYSQL_USER: '${DB_USERNAME:-guest}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'mysqldata:/var/lib/mysql'
        ports:
            - '3306:3306'
        networks:
            - app-network

volumes:
    mysqldata: null
    vendor_data:

networks:
    app-network:
        driver: bridge
